static const char *INDEX_HTML =
"<!DOCTYPE html>\n"
"<html>\n"
    "<head>\n"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "<meta charset=\"utf-8\"/>\n"
        "<script src=\"http://bernii.github.io/gauge.js/dist/gauge.min.js\"></script>\n"

// CSS
        "<style>\n"
            "body {\n"
                "min-width: 310px;\n"
                "max-width: 800px;\n"
                "height: 400px;\n"
                "margin: 0 auto;\n"
            "}"
            "h2 {"
                "font-family: Arial;\n"
                "font-size: 2.5rem;\n"
                "text-align: center;\n"
            "}"
            "h3 {"
                "font-family: Arial;\n"
                "font-size: 1.5rem;\n"
                "text-align: center;\n"
            "}"
            "canvas{"
                "margin-right: auto;"
                "margin-left: auto;"
                "display: block;"
            "}"
            "p {"
                "font-family: Arial;\n"
                "font-size: 1rem;\n"
                "text-align: center;\n"
            "}"
        "</style>\n"
    "</head>\n"

// BODY
   "<body>\n"
    "<h2>HomeAtmo</h2>\n"
        "<div><h3>Temperatur</h3><canvas id=\"chart-temperature\"></canvas><p id=\"temp\">0</p></div>\n"
        "<br />"
        "<br />"
        "<div><h3>Luftfreuchtigkeit</h3><canvas id=\"chart-humidity\"></canvas><p id=\"hum\">0</p></div>\n"
        "<br />"
        "<br />"
        "<div><h3>Luftdruck</h3><canvas id=\"chart-pressure\"></canvas><p id=\"press\">0</p></div>\n"
        "<br />"
        "<br />"
        "<div><h3>Luftqualität</h3><canvas id=\"chart-iaq\"></canvas><p id=\"iaq\">0</p></div>\n"
        "<br />"
        "<br />"
        "<div><h3>CO<sub>2</sub></h3><canvas id=\"chart-co2\"></canvas><p id=\"co2\">0</p></div>\n"
        "<br />"
        "<br />"
    "</body>\n"

// SCRIPT
    "<script>\n"
        "var opts = {"
            "angle: 0,"
            "lineWidth: 0.2,"
            "radiusScale: 0.89,"
            "pointer: {"
                "length: 0.54,"
                "strokeWidth: 0.053,"
                "color: '#000000'"
            "},"
            "strokeColor: '#E0E0E0',"
            // "generateGradient: true,"
            "highDpiSupport: true,"
            "percentColors: ["
                "[0.0, \"#00FF00\" ],"
                "[0.50, \"#FFFF00\"],"
                "[1.0, \"#FF0000\"]"
            "]"
        "};"
        // TEMPERATURE
        "var temperature_target = document.getElementById('chart-temperature');"
        "var temp_val = document.getElementById('temp');"
        "var temp_gauge = new Gauge(temperature_target).setOptions(opts);"
        "temp_gauge.maxValue = 40;"
        "temp_gauge.minValue = 15;"

        "var temp_request = new XMLHttpRequest();"
        "temp_request.onreadystatechange = function() {"
            "if (this.readyState == 4 && this.status == 200) {"
                "var y = parseFloat(this.responseText);"
                "temp_gauge.set(y);"
                "temp_val.innerHTML = y + \"°C\";"
            "}"
        "};"
        "temp_request.open(\"GET\", \"/temperature\", true);"
        "temp_request.send();"
        //HUMIDITY
        "var humidity_target = document.getElementById('chart-humidity');"
        "var hum_val = document.getElementById('hum');"
        "var hum_gauge = new Gauge(humidity_target).setOptions(opts);"
        "hum_gauge.maxValue = 100;"
        "hum_gauge.minValue = 0;"

        "var hum_request = new XMLHttpRequest();"
        "hum_request.onreadystatechange = function() {"
            "if (this.readyState == 4 && this.status == 200) {"
                "var y = parseFloat(this.responseText);"
                "hum_gauge.set(y);"
                "hum_val.innerHTML = y + \"%\";"
            "}"
        "};"
        "hum_request.open(\"GET\", \"/humidity\", true);"
        "hum_request.send();"
        // PRESSURE
        "var pressure_target = document.getElementById('chart-pressure');"
        "var press_val = document.getElementById('press');"
        "var press_gauge = new Gauge(pressure_target).setOptions(opts);"
        "press_gauge.maxValue = 1200;"
        "press_gauge.minValue = 900;"

        "var press_request = new XMLHttpRequest();"
        "press_request.onreadystatechange = function() {"
            "if (this.readyState == 4 && this.status == 200) {"
                "var y = parseFloat(this.responseText);"
                "press_gauge.set(y);"
                "press_val.innerHTML = y + \"hPa\";"
            "}"
        "};"
        "press_request.open(\"GET\", \"/pressure\", true);"
        "press_request.send();"
        // IAQ
        "var iaq_target = document.getElementById('chart-iaq');"
        "var iaq_val = document.getElementById('iaq');"
        "var iaq_gauge = new Gauge(iaq_target).setOptions(opts);"
        "iaq_gauge.maxValue = 300;"
        "iaq_gauge.minValue = 0;"

        "var iaq_request = new XMLHttpRequest();"
        "iaq_request.onreadystatechange = function() {"
            "if (this.readyState == 4 && this.status == 200) {"
                "var y = parseFloat(this.responseText);"
                "iaq_gauge.set(y);"
                "iaq_val.innerHTML = y;"
            "}"
        "};"
        "iaq_request.open(\"GET\", \"/iaq\", true);"
        "iaq_request.send();"
        // CO2
        "var co2_target = document.getElementById('chart-co2');"
        "var co2_val = document.getElementById('co2');"
        "var co2_gauge = new Gauge(co2_target).setOptions(opts);"
        "co2_gauge.maxValue = 3000;"
        "co2_gauge.minValue = 0;"

        "var co2_request = new XMLHttpRequest();"
        "co2_request.onreadystatechange = function() {"
            "if (this.readyState == 4 && this.status == 200) {"
                "var y = parseFloat(this.responseText);"
                "co2_gauge.set(y);"
                "co2_val.innerHTML = y + \"ppm\";"
            "}"
        "};"
        "co2_request.open(\"GET\", \"/co2\", true);"
        "co2_request.send();"
    "</script>\n"
"</html>\n";
